-- ==========================================
-- TESTOVACÍ DATA PRO MARKETPLACE
-- ==========================================
-- Vloží testovací influencery do databáze

INSERT INTO creators (
  name, 
  handle, 
  bio, 
  city, 
  price, 
  engagement, 
  premium, 
  verified, 
  categories, 
  platforms,
  followers_count,
  instagram_followers,
  instagram_connected,
  tiktok_followers,
  tiktok_connected,
  youtube_followers,
  youtube_connected
) VALUES 
(
  'Lucy Fitness',
  '@lucy.fit',
  'Rychlé dodání, čisté výstupy, vysoký engagement. Zaměřuji se na fitness a zdravou stravu.',
  'Praha',
  4900,
  6.2,
  true,
  true,
  ARRAY['fitness', 'food'],
  ARRAY['instagram', 'tiktok'],
  128000,
  85000,
  true,
  43000,
  true,
  0,
  false
),
(
  'Adam Tech',
  '@adam.tech',
  'Tech & gaming. Dobře fungují recenze produktů. Zaměřuji se na herní hardware a software.',
  'Brno',
  5900,
  4.1,
  false,
  false,
  ARRAY['gaming'],
  ARRAY['youtube', 'twitch'],
  82000,
  15000,
  true,
  12000,
  true,
  55000,
  true
),
(
  'Kája Daily',
  '@kaja.daily',
  'Beauty & lifestyle. Silná komunita. Pravidelně sdílím tipy pro každodenní péči.',
  'Bratislava',
  7900,
  5.4,
  false,
  true,
  ARRAY['beauty', 'travel'],
  ARRAY['instagram'],
  156000,
  156000,
  true,
  0,
  false,
  0,
  false
),
(
  'Martin Travel',
  '@martin.travel',
  'Cestování & gastro. Dobré na hotely a zážitky. Cestuji po celém světě.',
  'Praha',
  4500,
  3.7,
  false,
  true,
  ARRAY['travel', 'food'],
  ARRAY['instagram', 'youtube'],
  64000,
  42000,
  true,
  5000,
  true,
  17000,
  true
),
(
  'David Auto',
  '@auto.david',
  'Auta – virální formáty. Rychlé testy. Zaměřuji se na nejnovější automobily a technologie.',
  'Ostrava',
  9900,
  7.1,
  false,
  false,
  ARRAY['auta'],
  ARRAY['tiktok', 'instagram'],
  210000,
  95000,
  true,
  115000,
  true,
  0,
  false
)
ON CONFLICT (handle) DO NOTHING;
